/* Generated By:JJTree: Do not edit this line. ASTFalseNode.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package elastic.pl.interpreter;

public
class ASTFalseNode extends SimpleNode {
  public ASTFalseNode(int id) {
    super(id);
  }

  public ASTFalseNode(ElasticPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37e9dcc1ed0ccde7fa642103ed247801 (do not edit this line) */
