/* Generated By:JJTree: Do not edit this line. ASTNegationNode.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package elastic.pl.interpreter;

public
class ASTNegationNode extends SimpleNode {
  public ASTNegationNode(int id) {
    super(id);
  }

  public ASTNegationNode(ElasticPLParser p, int id) {
    super(p, id);
  }

  public void interpret()
  {
     jjtGetChild(0).interpret();

     Integer result = -(Integer)stack[top];
     stack[top] = result;
     mangle_state(result);



  }
  public String compile(){
    String n1 = ((SimpleNode)jjtGetChild(0)).compile();
    return "(-1*(" + n1 + "))";
  }
  public long getConsumedStackUsage(){
      return 0L;
    }
}
/* JavaCC - OriginalChecksum=52baa6ff1c44a5a391405672be5b682f (do not edit this line) */
