package elastic.pl.interpreter;

/* Generated By:JJTree: Do not edit this line. ASTSECP192K1PointAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSECP192K1PointAdd extends AbstractPointAdd {
  public ASTSECP192K1PointAdd(int id) {
    super(id);
  }

  public ASTSECP192K1PointAdd(ElasticPLParser p, int id) {
    super(p, id);
  }

  @Override
  public  String getCurve() { return "secp192k1"; }
  @Override
  public int getCompressedSize() {return 25; }
  @Override
  public int getUncompressedSize()  {return 49; }
  @Override
  public int getPrivkeyInputSize()  {return 24; }

}
/* JavaCC - OriginalChecksum=149c51669bb00582aa47fef7b7b566b1 (do not edit this line) */
