package elastic.pl.interpreter;

/* Generated By:JJTree: Do not edit this line. ASTSECP256K1PrivToPub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSECP256K1PrivToPub extends AbstractPrivToPub {
  public ASTSECP256K1PrivToPub(int id) {
    super(id);
  }

  public ASTSECP256K1PrivToPub(ElasticPLParser p, int id) {
    super(p, id);
  }

  @Override
  public  String getCurve() { return "secp256k1"; }
  @Override
  public int getCompressedSize() {return 33; }
  @Override
  public int getUncompressedSize()  {return 65; }
  @Override
  public int getPrivkeyInputSize()  {return 32; }

}
/* JavaCC - OriginalChecksum=b538b84394fa778d83874e548ead44b1 (do not edit this line) */
