/* Generated By:JJTree: Do not edit this line. ASTTrueNode.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package elastic.pl.interpreter;

public
class ASTTrueNode extends SimpleNode {
  public ASTTrueNode(int id) {
    super(id);
  }

  public ASTTrueNode(ElasticPLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e219c4a01de61c8b66fd66a04699fe2 (do not edit this line) */
