
/* Generated By:JJTree: Do not edit this line. ASTPRIME192V3PrivToPub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPRIME192V3PrivToPub extends AbstractPrivToPub {
  public ASTPRIME192V3PrivToPub(int id) {
    super(id);
  }

  public ASTPRIME192V3PrivToPub(ElasticPLParser p, int id) {
    super(p, id);
  }

  @Override
  public  String getCurve() { return "prime192v3"; }
  @Override
  public int getCompressedSize() {return 25; }
  @Override
  public int getUncompressedSize()  {return 49; }
  @Override
  public int getPrivkeyInputSize()  {return 24; }

}
/* JavaCC - OriginalChecksum=b538b84394fa778d83874e548ead44b1 (do not edit this line) */
