
/* Generated By:JJTree: Do not edit this line. ASTPRIME192V2PointNegate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPRIME192V2PointNegate extends AbstractPointNegate {
  public ASTPRIME192V2PointNegate(int id) {
    super(id);
  }

  public ASTPRIME192V2PointNegate(ElasticPLParser p, int id) {
    super(p, id);
  }

  @Override
  public  String getCurve() { return "prime192v2"; }
  @Override
  public int getCompressedSize() {return 25; }
  @Override
  public int getUncompressedSize()  {return 49; }
  @Override
  public int getPrivkeyInputSize()  {return 24; }
}
/* JavaCC - OriginalChecksum=4773d6afb2dcfb52e711792dda875863 (do not edit this line) */
