
/* Generated By:JJTree: Do not edit this line. ASTSECP192K1PointScalarMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSECP192K1PointScalarMult extends AbstractPointScalarMult {
  public ASTSECP192K1PointScalarMult(int id) {
    super(id);
  }

  public ASTSECP192K1PointScalarMult(ElasticPLParser p, int id) {
    super(p, id);
  }

  @Override
  public  String getCurve() { return "secp192k1"; }
  @Override
  public int getCompressedSize() {return 25; }
  @Override
  public int getUncompressedSize()  {return 49; }
  @Override
  public int getPrivkeyInputSize()  {return 24; }
}
/* JavaCC - OriginalChecksum=4b27c49383c76ca545598a0f80307d15 (do not edit this line) */

