/* Generated By:JJTree&JavaCC: Do not edit this line. ElasticPLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ElasticPLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 6;
  /** RegularExpression Id. */
  int IDENTIFIER = 50;
  /** RegularExpression Id. */
  int LETTER = 51;
  /** RegularExpression Id. */
  int DIGIT = 52;
  /** RegularExpression Id. */
  int DIGIT_FROM_ONE = 53;
  /** RegularExpression Id. */
  int DIGIT_ONE_TO_SIX = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"<<<\"",
    "\"~\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"m[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"repeat\"",
    "\"input\"",
    "\"SHA256\"",
    "\"SHA512\"",
    "\"MD5\"",
    "\"Tiger\"",
    "\"RIPEMD160\"",
    "\"RIPEMD128\"",
    "\"verify\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<DIGIT_FROM_ONE>",
    "<DIGIT_ONE_TO_SIX>",
  };

}
