/* Generated By:JavaCC: Do not edit this line. ElasticPLParserTreeConstants.java Version 5.0 */
public interface ElasticPLParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTASSIGNMENT = 2;
  public int JJTORNODE = 3;
  public int JJTANDNODE = 4;
  public int JJTBITWISEORNODE = 5;
  public int JJTBITWISEXORNODE = 6;
  public int JJTBITWISEANDNODE = 7;
  public int JJTEQNODE = 8;
  public int JJTNENODE = 9;
  public int JJTLTNODE = 10;
  public int JJTGTNODE = 11;
  public int JJTLENODE = 12;
  public int JJTGENODE = 13;
  public int JJTADDNODE = 14;
  public int JJTSUBTRACTNODE = 15;
  public int JJTMULNODE = 16;
  public int JJTDIVNODE = 17;
  public int JJTMODNODE = 18;
  public int JJTLSHIFTNODE = 19;
  public int JJTRSHIFTNODE = 20;
  public int JJTRROTNODE = 21;
  public int JJTLROTNODE = 22;
  public int JJTBITWISECOMPLNODE = 23;
  public int JJTNOTNODE = 24;
  public int JJTID = 25;
  public int JJTINTCONSTNODE = 26;
  public int JJTTRUENODE = 27;
  public int JJTFALSENODE = 28;
  public int JJTBLOCK = 29;
  public int JJTSTATEMENTEXPRESSION = 30;
  public int JJTIFSTATEMENT = 31;
  public int JJTREPEATSTATEMENT = 32;
  public int JJTINPUTSPECIFICATIONSTATEMENT = 33;
  public int JJTSHA256 = 34;
  public int JJTSHA512 = 35;
  public int JJTWHIRLPOOL = 36;
  public int JJTMD5 = 37;
  public int JJTTIGER = 38;
  public int JJTRIPEMD160 = 39;
  public int JJTRIPEMD128 = 40;
  public int JJTVERIFYSTATEMENT = 41;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Assignment",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "LShiftNode",
    "RShiftNode",
    "RRotNode",
    "LRotNode",
    "BitwiseComplNode",
    "NotNode",
    "Id",
    "IntConstNode",
    "TrueNode",
    "FalseNode",
    "Block",
    "StatementExpression",
    "IfStatement",
    "RepeatStatement",
    "InputSpecificationStatement",
    "SHA256",
    "SHA512",
    "Whirlpool",
    "MD5",
    "Tiger",
    "RIPEMD160",
    "RIPEMD128",
    "VerifyStatement",
  };
}
/* JavaCC - OriginalChecksum=835d57fa79036f032898b8b1f8d797fe (do not edit this line) */
