package elastic.pl.interpreter;

/* Generated By:JJTree: Do not edit this line. ASTPRIME192V2PointScalarMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPRIME192V2PointScalarMult extends AbstractPointScalarMult {
  public ASTPRIME192V2PointScalarMult(int id) {
    super(id);
  }

  public ASTPRIME192V2PointScalarMult(ElasticPLParser p, int id) {
    super(p, id);
  }

  @Override
  public  String getCurve() { return "prime192v2"; }
  @Override
  public int getCompressedSize() {return 25; }
  @Override
  public int getUncompressedSize()  {return 49; }
  @Override
  public int getPrivkeyInputSize()  {return 24; }
}
/* JavaCC - OriginalChecksum=4b27c49383c76ca545598a0f80307d15 (do not edit this line) */

