package elastic.pl.interpreter;

/* Generated By:JJTree: Do not edit this line. ASTSECP384R1PointScalarMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSECP384R1PointScalarMult extends AbstractPointScalarMult {
  public ASTSECP384R1PointScalarMult(int id) {
    super(id);
  }

  public ASTSECP384R1PointScalarMult(ElasticPLParser p, int id) {
    super(p, id);
  }

  @Override
  public  String getCurve() { return "secp384r1"; }
  @Override
  public int getCompressedSize() {return 49; }
  @Override
  public int getUncompressedSize()  {return 97; }
  @Override
  public int getPrivkeyInputSize()  {return 48; }
}
/* JavaCC - OriginalChecksum=4b27c49383c76ca545598a0f80307d15 (do not edit this line) */

